export const languages = [
  { name: 'English (US)', code: 'en-US' },
  { name: 'Spanish', code: 'es-ES' },
  { name: 'French', code: 'fr-FR' },
  { name: 'German', code: 'de-DE' },
  { name: 'Italian', code: 'it-IT' },
  { name: 'Portuguese', code: 'pt-PT' },
  { name: 'Russian', code: 'ru-RU' },
  { name: 'Chinese (Simplified)', code: 'zh-CN' },
  { name: 'Japanese', code: 'ja-JP' },
  { name: 'Korean', code: 'ko-KR' },
  { name: 'Arabic', code: 'ar-SA' },
  { name: 'Hindi', code: 'hi-IN' },
  { name: 'Bengali', code: 'bn-IN' },
  { name: 'Urdu', code: 'ur-PK' },
  { name: 'Swahili', code: 'sw-KE' },
  { name: 'Vietnamese', code: 'vi-VN' },
  { name: 'Thai', code: 'th-TH' },
  { name: 'Turkish', code: 'tr-TR' },
];